In [1]:
from pathpyG.algorithms.RandomGraphs import Watts_Strogatz, Molloy_Reed

In [2]:
import pathpyG as pp

In [3]:
import torch

In [4]:
degree_sequence = torch.tensor([3, 2, 2, 1, 1, 1])

In [5]:
nodes = torch.arange(len(degree_sequence))
nodes

tensor([0, 1, 2, 3, 4, 5])

In [6]:
stubs = nodes.repeat_interleave(degree_sequence)
stubs = stubs[torch.randperm(len(stubs))]
edges = torch.stack([stubs[i::2] for i in range(2)], dim=-1)
edges

tensor([[0, 0],
        [4, 5],
        [0, 1],
        [2, 1],
        [2, 3]])

In [7]:
# Remove self-loops
edges = edges[edges[:, 0] != edges[:, 1]]
edges

tensor([[4, 5],
        [0, 1],
        [2, 1],
        [2, 3]])

In [8]:
# Sort each edge for comparison
edges = torch.sort(edges, dim=1)[0]
edges

tensor([[4, 5],
        [0, 1],
        [1, 2],
        [2, 3]])

In [9]:
# Remove repeated edges
edges, tt = torch.unique(edges, dim=0, return_counts=True)
edges

tensor([[0, 1],
        [1, 2],
        [2, 3],
        [4, 5]])

In [10]:
edges[torch.randint(edges.shape[0], (1,))][0]

tensor([1, 2])

In [11]:
tt

tensor([1, 1, 1, 1])

In [12]:
g = Molloy_Reed(torch.tensor([3, 2, 2, 1, 1, 1]))
torch.tensor(list(g.in_degrees.values())) #+ torch.tensor(list(g.out_degrees.values()))

Edges first: tensor([[2, 5],
        [1, 0],
        [4, 2],
        [1, 3],
        [0, 0]])
Edges after first self-loop removal: tensor([[2, 5],
        [1, 0],
        [4, 2],
        [1, 3]])
Stubs after first self-loop removal: tensor([0, 0])
Removed edge: tensor([[1, 0]])
Stubs after edge removal: tensor([0, 0, 1, 0])
Edges after edge removal and restubbing: tensor([[2, 5],
        [1, 0],
        [4, 2],
        [1, 3],
        [0, 0],
        [0, 1]])
Edges after second self-loop removal: tensor([[2, 5],
        [1, 0],
        [4, 2],
        [1, 3],
        [0, 1]])
Stubs after second self-loop removal: tensor([0, 0])
Removed edge: tensor([[1, 0]])
Stubs after edge removal: tensor([0, 0, 1, 0])
Edges after edge removal and restubbing: tensor([[2, 5],
        [1, 0],
        [4, 2],
        [1, 3],
        [0, 1],
        [0, 0],
        [0, 1]])
Edges after second self-loop removal: tensor([[2, 5],
        [1, 0],
        [4, 2],
        [1, 3],
        [0, 1],
        [0, 1]

tensor([3, 2, 3, 1, 1, 2])

In [32]:
g.in_degrees

{0: 3, 1: 2, 2: 2, 3: 1, 4: 1, 5: 1}

In [33]:
g.out_degrees

{0: 3, 1: 2, 2: 2, 3: 1, 4: 1, 5: 1}

In [13]:
def test_molloy_reed():
    g = Molloy_Reed(torch.tensor([3, 2, 2, 1, 1, 1]), undirected=False)
    assert g.N == 6
    assert set(g.degrees().keys()) == {0, 1, 2, 3, 4, 5}
    assert set(g.degrees().values()) == {1, 2, 3}
    assert g.is_directed() == True

    g = Molloy_Reed(torch.tensor([3, 2, 2, 1, 1, 1]), mapping=pp.IndexMap(['a', 'b', 'c', 'd', 'e', 'f']))
    assert g.N == 6
    assert set(g.degrees().keys()) == {'a', 'b', 'c', 'd', 'e', 'f'}
    assert set(g.degrees().values()) == {1, 2, 3}
    assert g.is_directed() == False

In [14]:
test_molloy_reed()

TypeError: Molloy_Reed() got an unexpected keyword argument 'undirected'

In [ ]:
g = Molloy_Reed(torch.tensor([3, 2, 2, 1, 1, 1]), undirected=True)

In [ ]:
set(g.degrees().values())

{1, 2}

In [ ]:
import pathpy as pp

In [ ]:
from pathpy.generators.random_graphs import Molloy_Reed
g = Molloy_Reed([3, 2, 2, 1, 1, 1])
g.number_of_edges()

5

In [ ]:
g.degrees()

{'0': 3, '1': 2, '2': 2, '3': 1, '4': 1, '5': 1}