In [1]:
import pathpyG as pp
print('Running on', pp.config['torch']['device'])
import torch
from pathpyG.processes.random_walk import RandomWalk, HigherOrderRandomWalk


Running on cpu


In [2]:
g = pp.io.read_netzschleuder_network('karate', '77')
print(g)

Undirected graph with 34 nodes and 154 (directed) edges

Node attributes
	node__pos		<class 'list'>
	node_name		<class 'list'>
	node_groups		<class 'list'>

Graph attributes
	url		<class 'str'>
	citation		<class 'str'>
	description		<class 'str'>
	name		<class 'str'>
	tags		<class 'list'>
	num_nodes		<class 'int'>



In [3]:
rw = RandomWalk(g)

In [4]:
data = rw.run_experiment(steps=100,runs=range(34))

100%|██████████| 34/34 [00:00<00:00, 347.70it/s]


In [5]:
data

run_id  seed  time  node  state
0          0     0     0     0   True
1          0     0     0     1  False
2          0     0     0     2  False
3          0     0     0     3  False
4          0     0     0     4  False
...      ...   ...   ...   ...    ...
7951      33    33    98     1  False
7952      33    33    99     0   True
7953      33    33    99    21  False
7954      33    33   100     3   True
7955      33    33   100     0  False

[7956 rows x 5 columns]

In [7]:
paths = rw.get_paths(data)

[0, 8, 32, 31, 32, 22, 32, 8, 33, 30, 1, 30, 32, 20, 33, 14, 32, 15, 33, 13, 1, 21, 1, 30, 33, 13, 1, 19, 1, 7, 0, 13, 33, 9, 33, 18, 33, 13, 0, 5, 6, 0, 1, 2, 7, 0, 12, 0, 12, 0, 17, 1, 30, 32, 23, 32, 22, 32, 23, 25, 24, 25, 23, 33, 23, 29, 33, 27, 24, 25, 23, 25, 24, 27, 23, 25, 23, 27, 24, 31, 33, 23, 33, 13, 2, 7, 0, 19, 0, 6, 16, 5, 10, 0, 5, 10, 0, 19, 33, 27, 24]
[1, 0, 31, 0, 5, 6, 4, 6, 16, 6, 16, 6, 0, 1, 30, 32, 31, 32, 30, 1, 30, 33, 20, 32, 2, 8, 2, 28, 2, 0, 10, 4, 6, 4, 10, 0, 8, 32, 20, 32, 18, 32, 31, 24, 25, 31, 25, 31, 32, 2, 27, 2, 3, 1, 3, 13, 33, 29, 23, 29, 32, 29, 33, 30, 33, 23, 29, 32, 20, 33, 29, 26, 33, 28, 31, 25, 23, 29, 32, 14, 32, 14, 33, 32, 2, 28, 2, 3, 2, 32, 8, 32, 18, 33, 9, 2, 28, 33, 27, 33, 29]
[2, 0, 19, 33, 31, 32, 30, 1, 3, 0, 21, 1, 7, 0, 19, 1, 3, 2, 27, 2, 13, 2, 27, 33, 23, 33, 29, 32, 33, 20, 32, 20, 33, 32, 33, 31, 25, 23, 27, 33, 9, 33, 30, 8, 30, 8, 0, 19, 33, 15, 32, 29, 23, 25, 24, 27, 33, 27, 2, 28, 31, 24, 25, 24, 27, 24, 25, 31, 

In [14]:
paths.dags[0].edge_index

tensor([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
          14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
          28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,
          42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,
          56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,
          70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,
          84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,
          98,  99],
        [  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,
          15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,
          29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,
          43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,
          57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,
          71,  72,  73,  74,  75

In [8]:
m = pp.MultiOrderModel.from_DAGs(paths, max_order=3)
g2 = m.layers[2]
print(g2)

Directed graph with 154 nodes and 1005 edges

Node attributes
	node_sequences		<class 'torch.Tensor'> -> torch.Size([154, 2])

Edge attributes
	edge_weight		<class 'torch.Tensor'> -> torch.Size([1005])

Graph attributes
	num_nodes		<class 'int'>



In [9]:
#print(g_ho)

In [10]:
#for v in g_ho.nodes:
#    print(v)

In [9]:
g2= pp.Graph.from_edge_list([
    ['a', 'b'],
    ['b', 'c'],
    ['c', 'd'],
    ['d', 'e'],
    ['e', 'f'],
    ['f', 'g'],
    ['g', 'h'],
    ['h', 'i'],
    ['i', 'j'],
    ['j', 'k'],
    ['k', 'l'],
    ['l', 'm'],
    ['m', 'n'],
    ['n', 'o'],
    ['o', 'a']
])

In [10]:
g2.mapping.to_idx('b')

1

In [11]:
rw2 = RandomWalk(g2)

In [13]:
data2 = rw2.run_experiment(steps=20,runs=['a','b'])

100%|██████████| 2/2 [00:00<00:00, 1900.02it/s]


In [15]:
data2

run_id seed  time node  state
0         0    a     0    a   True
1         0    a     0    b  False
2         0    a     0    c  False
3         0    a     0    d  False
4         0    a     0    e  False
..      ...  ...   ...  ...    ...
105       1    b    18    d  False
106       1    b    19    f   True
107       1    b    19    e  False
108       1    b    20    g   True
109       1    b    20    f  False

[110 rows x 5 columns]

In [16]:
paths2 = rw2.get_paths(data2)

paths2.paths

{0: tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14,  0,  1,  2,
           3,  4],
         [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14,  0,  1,  2,  3,
           4,  5]], dtype=torch.int32),
 1: tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14,  0,  1,  2,  3,
           4,  5],
         [ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14,  0,  1,  2,  3,  4,
           5,  6]], dtype=torch.int32)}

In [17]:
pp.plot(g2);

In [18]:
g2.mapping.idx_to_id

{0: 'a',
 1: 'b',
 2: 'c',
 3: 'd',
 4: 'e',
 5: 'f',
 6: 'g',
 7: 'h',
 8: 'i',
 9: 'j',
 10: 'k',
 11: 'l',
 12: 'm',
 13: 'n',
 14: 'o'}

In [19]:
g2_ho = pp.HigherOrderGraph(paths2, order = 2)

In [20]:
pp.plot(g2_ho,node_label=[g2_ho.mapping.to_id(x) for x in range(g2_ho.n)]);

# Higher Order Random Walk

In [14]:
g3 = pp.Graph.from_edge_list([
    ['a','b'],
    ['b','c'],
    ['c','a'],
    ['c','d'],
    ['d','a']
    ])

g3.data['edge_weight'] = torch.tensor([[1],[1],[2],[1],[1]])

In [15]:
pp.plot(g3, node_label= [g3.mapping.to_id(x) for x in range(g3.n)]);

In [23]:
g3.mapping.id_to_idx

{'a': 0, 'b': 1, 'c': 2, 'd': 3}

In [18]:
paths = pp.DAGData(g3.mapping)
paths.append_walk(['a','b','c'],weight=1)
paths.append_walk(['b','c','a'],weight=1)
paths.append_walk(['b','c','d'],weight=0.2)
paths.append_walk(['c','a','b'],weight=1)
paths.append_walk(['c','d','a'],weight=0.2)
paths.append_walk(['d','a','b'],weight=1)

In [19]:
paths.dags

[Data(edge_index=[2, 2], node_sequences=[3, 1], num_nodes=3, weight=1),
 Data(edge_index=[2, 2], node_sequences=[3, 1], num_nodes=3, weight=1),
 Data(edge_index=[2, 2], node_sequences=[3, 1], num_nodes=3, weight=0.20000000298023224),
 Data(edge_index=[2, 2], node_sequences=[3, 1], num_nodes=3, weight=1),
 Data(edge_index=[2, 2], node_sequences=[3, 1], num_nodes=3, weight=0.20000000298023224),
 Data(edge_index=[2, 2], node_sequences=[3, 1], num_nodes=3, weight=1)]

In [20]:
m = pp.MultiOrderModel.from_DAGs(paths, max_order=3)
g3_ho = m.layers[2]

In [22]:
pp.plot(g3_ho, node_label = [g3_ho.mapping.to_id(x) for x in range(g3_ho.n)]);

In [23]:
rw = HigherOrderRandomWalk(g3_ho, g3, weight=True)

In [24]:
data = rw.run_experiment(steps=100, runs=list(g3_ho.nodes))

100%|██████████| 5/5 [00:00<00:00, 511.38it/s]


In [25]:
data

run_id    seed  time    node  state
0          0  (a, b)     0  (a, b)   True
1          0  (a, b)     0  (b, c)  False
2          0  (a, b)     0  (c, a)  False
3          0  (a, b)     0  (c, d)  False
4          0  (a, b)     0  (d, a)  False
...      ...     ...   ...     ...    ...
1020       4  (d, a)    98  (b, c)  False
1021       4  (d, a)    99  (d, a)   True
1022       4  (d, a)    99  (c, d)  False
1023       4  (d, a)   100  (a, b)   True
1024       4  (d, a)   100  (d, a)  False

[1025 rows x 5 columns]

In [29]:
path = rw.get_paths(data,[0,1])
print(path)

DAGData with 2 dags with total weight 2.0


In [30]:
path.get_walk(0)

('a',
 'b',
 'c',
 'd',
 'a',
 'b',
 'c',
 'd',
 'a',
 'b',
 'c',
 'a',
 'b',
 'c',
 'a',
 'b',
 'c',
 'd',
 'a',
 'b',
 'c',
 'a',
 'b',
 'c',
 'a',
 'b',
 'c',
 'a',
 'b',
 'c',
 'a',
 'b',
 'c',
 'a',
 'b',
 'c',
 'a',
 'b',
 'c',
 'd',
 'a',
 'b',
 'c',
 'a',
 'b',
 'c',
 'd',
 'a',
 'b',
 'c',
 'd',
 'a',
 'b',
 'c',
 'd',
 'a',
 'b',
 'c',
 'd',
 'a',
 'b',
 'c',
 'a',
 'b',
 'c',
 'd',
 'a',
 'b',
 'c',
 'a',
 'b',
 'c',
 'a',
 'b',
 'c',
 'a',
 'b',
 'c',
 'd',
 'a',
 'b',
 'c',
 'd',
 'a',
 'b',
 'c',
 'a',
 'b',
 'c',
 'd',
 'a',
 'b',
 'c',
 'd',
 'a',
 'b',
 'c',
 'a',
 'b',
 'c',
 'a',
 'b')

In [51]:
g3.mapping.idx_to_id

{0: 'a', 1: 'b', 2: 'c', 3: 'd'}

In [56]:
for time,_ in rw.simulation_run(steps=50, seed=('a','b')):
    print('Current node = {0}'.format(rw.first_order_node(rw.current_node)))
    print(rw._first_order_visitations)


Current node = c
[0. 1. 1. 0.]
Current node = a
[1. 1. 1. 0.]
Current node = b
[1. 2. 1. 0.]
Current node = c
[1. 2. 2. 0.]
Current node = a
[2. 2. 2. 0.]
Current node = b
[2. 3. 2. 0.]
Current node = c
[2. 3. 3. 0.]
Current node = a
[3. 3. 3. 0.]
Current node = b
[3. 4. 3. 0.]
Current node = c
[3. 4. 4. 0.]
Current node = a
[4. 4. 4. 0.]
Current node = b
[4. 5. 4. 0.]
Current node = c
[4. 5. 5. 0.]
Current node = d
[4. 5. 5. 1.]
Current node = a
[5. 5. 5. 1.]
Current node = b
[5. 6. 5. 1.]
Current node = c
[5. 6. 6. 1.]
Current node = d
[5. 6. 6. 2.]
Current node = a
[6. 6. 6. 2.]
Current node = b
[6. 7. 6. 2.]
Current node = c
[6. 7. 7. 2.]
Current node = a
[7. 7. 7. 2.]
Current node = b
[7. 8. 7. 2.]
Current node = c
[7. 8. 8. 2.]
Current node = a
[8. 8. 8. 2.]
Current node = b
[8. 9. 8. 2.]
Current node = c
[8. 9. 9. 2.]
Current node = d
[8. 9. 9. 3.]
Current node = a
[9. 9. 9. 3.]
Current node = b
[ 9. 10.  9.  3.]
Current node = c
[ 9. 10. 10.  3.]
Current node = a
[10. 10. 10.  