In [1]:
import pathpyG as pp

print('Running on', pp.config['torch']['device'])

In [2]:
paths = pp.GlobalPathStorage.from_csv('../data/temporal_clusters.ngram')

In [3]:
print(paths)

PathStorage with 7460 paths


In [4]:
paths['path_index']

{0: tensor([[0, 1],
         [1, 2]], device='cuda:0', dtype=torch.int32),
 1: tensor([[3, 4],
         [4, 5]], device='cuda:0', dtype=torch.int32),
 2: tensor([[5, 6],
         [6, 1]], device='cuda:0', dtype=torch.int32),
 3: tensor([[3, 2],
         [2, 7]], device='cuda:0', dtype=torch.int32),
 4: tensor([[ 8,  9],
         [ 9, 10]], device='cuda:0', dtype=torch.int32),
 5: tensor([[11, 12],
         [12,  8]], device='cuda:0', dtype=torch.int32),
 6: tensor([[13, 14],
         [14,  1]], device='cuda:0', dtype=torch.int32),
 7: tensor([[15,  1],
         [ 1, 16]], device='cuda:0', dtype=torch.int32),
 8: tensor([[16, 17],
         [17, 18]], device='cuda:0', dtype=torch.int32),
 9: tensor([[16,  2],
         [ 2,  7]], device='cuda:0', dtype=torch.int32),
 10: tensor([[ 3,  4],
         [ 4, 19]], device='cuda:0', dtype=torch.int32),
 11: tensor([[16,  1],
         [ 1, 12]], device='cuda:0', dtype=torch.int32),
 12: tensor([[ 2, 20],
         [20,  6]], device='cuda:0', dtype=

In [13]:
g2 = pp.HigherOrderGraph(paths, order=2)
print(g2)
print(g2['edge_index'])

HigherOrderGraph (k=2) with 560 nodes and 6789 edges

Edge attributes
	edge_weight		<class 'torch.Tensor'> -> torch.Size([6789])

Graph attributes
	num_nodes		<class 'int'>
	node_id		<class 'list'>

tensor([[  0,   0,   0,  ..., 559, 559, 559],
        [ 18,  19,  20,  ..., 519, 520, 521]], device='cuda:0')


In [6]:
g2.edge_to_index

{(0, 18): 0,
 (0, 19): 1,
 (0, 20): 2,
 (0, 21): 3,
 (0, 22): 4,
 (0, 23): 5,
 (0, 24): 6,
 (0, 25): 7,
 (0, 28): 8,
 (0, 29): 9,
 (0, 30): 10,
 (0, 31): 11,
 (0, 32): 12,
 (0, 33): 13,
 (0, 34): 14,
 (0, 35): 15,
 (0, 36): 16,
 (1, 38): 17,
 (1, 41): 18,
 (1, 42): 19,
 (1, 46): 20,
 (1, 48): 21,
 (1, 49): 22,
 (1, 50): 23,
 (1, 52): 24,
 (1, 55): 25,
 (1, 56): 26,
 (2, 73): 27,
 (2, 75): 28,
 (2, 78): 29,
 (2, 80): 30,
 (2, 81): 31,
 (2, 83): 32,
 (2, 84): 33,
 (2, 86): 34,
 (2, 88): 35,
 (2, 90): 36,
 (3, 91): 37,
 (3, 92): 38,
 (3, 94): 39,
 (3, 95): 40,
 (3, 96): 41,
 (3, 97): 42,
 (3, 98): 43,
 (3, 99): 44,
 (3, 101): 45,
 (3, 103): 46,
 (3, 104): 47,
 (3, 106): 48,
 (3, 109): 49,
 (3, 110): 50,
 (3, 111): 51,
 (3, 112): 52,
 (3, 113): 53,
 (4, 114): 54,
 (4, 117): 55,
 (4, 122): 56,
 (4, 123): 57,
 (4, 128): 58,
 (4, 130): 59,
 (5, 146): 60,
 (5, 147): 61,
 (5, 148): 62,
 (5, 151): 63,
 (5, 152): 64,
 (5, 153): 65,
 (5, 154): 66,
 (5, 155): 67,
 (5, 158): 68,
 (5, 159): 69,
 (5, 

In [7]:
g2['edge_index'][:,5]

tensor([ 0, 23], device='cuda:0')

In [8]:
g2.node_index_to_id

{0: (0, 1),
 1: (0, 2),
 2: (0, 4),
 3: (0, 5),
 4: (0, 6),
 5: (0, 8),
 6: (0, 9),
 7: (0, 11),
 8: (0, 12),
 9: (0, 14),
 10: (0, 16),
 11: (0, 17),
 12: (0, 18),
 13: (0, 19),
 14: (0, 22),
 15: (0, 23),
 16: (0, 26),
 17: (0, 28),
 18: (1, 0),
 19: (1, 2),
 20: (1, 3),
 21: (1, 4),
 22: (1, 6),
 23: (1, 9),
 24: (1, 10),
 25: (1, 11),
 26: (1, 12),
 27: (1, 13),
 28: (1, 14),
 29: (1, 15),
 30: (1, 16),
 31: (1, 17),
 32: (1, 18),
 33: (1, 20),
 34: (1, 22),
 35: (1, 23),
 36: (1, 25),
 37: (1, 29),
 38: (2, 0),
 39: (2, 1),
 40: (2, 3),
 41: (2, 4),
 42: (2, 5),
 43: (2, 7),
 44: (2, 12),
 45: (2, 13),
 46: (2, 15),
 47: (2, 16),
 48: (2, 17),
 49: (2, 19),
 50: (2, 20),
 51: (2, 21),
 52: (2, 22),
 53: (2, 23),
 54: (2, 24),
 55: (2, 25),
 56: (2, 26),
 57: (3, 1),
 58: (3, 2),
 59: (3, 4),
 60: (3, 5),
 61: (3, 7),
 62: (3, 8),
 63: (3, 9),
 64: (3, 10),
 65: (3, 11),
 66: (3, 13),
 67: (3, 14),
 68: (3, 15),
 69: (3, 17),
 70: (3, 20),
 71: (3, 24),
 72: (3, 27),
 73: (4, 0),
 

In [10]:
# Topology of first-order graph
paths.edge_index

tensor([[ 0,  1,  3,  ...,  4, 21,  4],
        [ 1,  2,  4,  ..., 21,  4, 25]], device='cuda:0', dtype=torch.int32)

In [11]:
paths.edge_index_k(k=2)

tensor([[[ 0,  1],
         [ 3,  4],
         [ 5,  6],
         ...,
         [18,  4],
         [ 4, 21],
         [21,  4]],

        [[ 1,  2],
         [ 4,  5],
         [ 6,  1],
         ...,
         [ 4, 21],
         [21,  4],
         [ 4, 25]]], device='cuda:0', dtype=torch.int32)

In [9]:
g2.node_id_to_index

{(0, 1): 0,
 (0, 2): 1,
 (0, 4): 2,
 (0, 5): 3,
 (0, 6): 4,
 (0, 8): 5,
 (0, 9): 6,
 (0, 11): 7,
 (0, 12): 8,
 (0, 14): 9,
 (0, 16): 10,
 (0, 17): 11,
 (0, 18): 12,
 (0, 19): 13,
 (0, 22): 14,
 (0, 23): 15,
 (0, 26): 16,
 (0, 28): 17,
 (1, 0): 18,
 (1, 2): 19,
 (1, 3): 20,
 (1, 4): 21,
 (1, 6): 22,
 (1, 9): 23,
 (1, 10): 24,
 (1, 11): 25,
 (1, 12): 26,
 (1, 13): 27,
 (1, 14): 28,
 (1, 15): 29,
 (1, 16): 30,
 (1, 17): 31,
 (1, 18): 32,
 (1, 20): 33,
 (1, 22): 34,
 (1, 23): 35,
 (1, 25): 36,
 (1, 29): 37,
 (2, 0): 38,
 (2, 1): 39,
 (2, 3): 40,
 (2, 4): 41,
 (2, 5): 42,
 (2, 7): 43,
 (2, 12): 44,
 (2, 13): 45,
 (2, 15): 46,
 (2, 16): 47,
 (2, 17): 48,
 (2, 19): 49,
 (2, 20): 50,
 (2, 21): 51,
 (2, 22): 52,
 (2, 23): 53,
 (2, 24): 54,
 (2, 25): 55,
 (2, 26): 56,
 (3, 1): 57,
 (3, 2): 58,
 (3, 4): 59,
 (3, 5): 60,
 (3, 7): 61,
 (3, 8): 62,
 (3, 9): 63,
 (3, 10): 64,
 (3, 11): 65,
 (3, 13): 66,
 (3, 14): 67,
 (3, 15): 68,
 (3, 17): 69,
 (3, 20): 70,
 (3, 24): 71,
 (3, 27): 72,
 (4, 0): 73,
 

In [14]:
g2['edge_index']

tensor([[  0,   0,   0,  ..., 559, 559, 559],
        [ 18,  19,  20,  ..., 519, 520, 521]], device='cuda:0')

In [15]:
g2.to_pyg_data()

Data(edge_index=[2, 6789], num_nodes=560, node_id=[0], edge_weight=[6789])