In [1]:
from pathpyG.core.PathData import PathData
from pathpyG.core.WalkData import WalkData
from pathpyG.core.DAGData import DAGData

from torch import IntTensor

import pathpyG as pp

pp.config['torch']['device'] = 'cpu'

In [2]:
g = pp.Graph.from_edge_list([('a', 'c'),
                             ('b', 'c'),
                             ('c', 'd'),
                             ('c','e')])
pp.plot(g, node_label=g.mapping.node_ids, edge_color='gray')

## Data on Walks

In [3]:
path = IntTensor([[0,1],
                  [1,3]])
WalkData.edge_index_kth_order(path, k=1)

tensor([[[0],
         [1]],

        [[1],
         [3]]], dtype=torch.int32)

In [4]:
WalkData.edge_index_kth_order(path, k=2)

tensor([[[0, 1]],

        [[1, 3]]], dtype=torch.int32)

In [5]:
paths_1 = WalkData(g.mapping)
paths_1.add_walk_seq(('a', 'c', 'd'), freq=2)
paths_1.add_walk_seq(('b', 'c', 'e'), freq=2)
print(paths_1.paths)
print(paths_1.path_freq)

{0: tensor([[0, 1],
        [1, 3]], dtype=torch.int32), 1: tensor([[2, 1],
        [1, 4]], dtype=torch.int32)}
{0: 2, 1: 2}


In [6]:
paths_1.edge_index

tensor([[0, 1, 1, 2],
        [1, 3, 4, 1]], dtype=torch.int32)

In [7]:
paths_1.edge_index_weighted

(tensor([[0, 1, 1, 2],
         [1, 3, 4, 1]], dtype=torch.int32),
 tensor([2., 2., 2., 2.]))

In [8]:
paths_1.edge_index_k_weighted(k=2)

(tensor([[[0, 1],
          [2, 1]],
 
         [[1, 3],
          [1, 4]]], dtype=torch.int32),
 tensor([2., 2.]))

In [9]:
paths_2 = WalkData(g.mapping)
paths_2.add_walk_seq(('a', 'c', 'd'), freq=1)
paths_2.add_walk_seq(('a', 'c', 'e'), freq=1)
paths_2.add_walk_seq(('b', 'c', 'd'), freq=1)
paths_2.add_walk_seq(('b', 'c', 'e'), freq=1)
print(paths_2.paths)
print(paths_2.path_freq)

{0: tensor([[0, 1],
        [1, 3]], dtype=torch.int32), 1: tensor([[0, 1],
        [1, 4]], dtype=torch.int32), 2: tensor([[2, 1],
        [1, 3]], dtype=torch.int32), 3: tensor([[2, 1],
        [1, 4]], dtype=torch.int32)}
{0: 1, 1: 1, 2: 1, 3: 1}


In [10]:
paths_2.edge_index_weighted

(tensor([[0, 1, 1, 2],
         [1, 3, 4, 1]], dtype=torch.int32),
 tensor([2., 2., 2., 2.]))

In [11]:
paths_2.edge_index_k_weighted(k=2)

(tensor([[[0, 1],
          [0, 1],
          [2, 1],
          [2, 1]],
 
         [[1, 3],
          [1, 4],
          [1, 3],
          [1, 4]]], dtype=torch.int32),
 tensor([1., 1., 1., 1.]))

# Data on directed acyclic graphs

In [12]:
path = IntTensor([[0,2,2],
                  [2,3,4]])
DAGData.edge_index_kth_order(path, k=2)

tensor([[[0, 2],
         [0, 2]],

        [[2, 3],
         [2, 4]]], dtype=torch.int32)

In [13]:
paths_1 = DAGData(g.mapping)
dag = IntTensor([[0,2,2],
                  [2,3,4]])
paths_1.add(dag, freq=1)
dag = IntTensor([[1,2,2],
                  [2,3,4]])
paths_1.add(dag, freq=1)

In [14]:
paths_1.edge_index_weighted

(tensor([[0, 1, 2, 2],
         [2, 2, 3, 4]], dtype=torch.int32),
 tensor([1., 1., 2., 2.]))

In [15]:
paths_1.edge_index_k_weighted(k=2)

(tensor([[[0, 2],
          [0, 2],
          [1, 2],
          [1, 2]],
 
         [[2, 3],
          [2, 4],
          [2, 3],
          [2, 4]]], dtype=torch.int32),
 tensor([1., 1., 1., 1.]))