In [1]:
from pathpyG.core.PathData import PathData
from torch import IntTensor

import pathpyG as pp

pp.config['torch']['device'] = 'cpu'

In [2]:
paths = PathData()
paths.add_walk(IntTensor([[0,1,2],[1,2,3]]), freq=2)
paths.add_dag(IntTensor([[0,1,1],[1,2,3]]), freq=3)
print(paths.paths)
print(paths.path_types)
print(paths.path_freq)

{0: tensor([[0, 1, 2],
        [1, 2, 3]], dtype=torch.int32), 1: tensor([[0, 1, 1],
        [1, 2, 3]], dtype=torch.int32)}
{0: <PathType.WALK: 0>, 1: <PathType.DAG: 1>}
{0: 2, 1: 3}


In [3]:
paths.edge_index

torch.Size([2, 6])
tensor([2., 2., 2., 3., 3., 3.])
[tensor([[0],
        [3]]), tensor([[1],
        [4]]), tensor([[5]]), tensor([[2]])]


tensor([[0, 1, 1, 2],
        [1, 2, 3, 3]], dtype=torch.int32)

In [8]:
paths.edge_index_k_weighted(k=2)

torch.Size([2, 4, 2])
tensor([2., 2., 3., 3.])
[tensor([[0],
        [2]]), tensor([[3]]), tensor([[1]])]


(tensor([[[0, 1],
          [0, 1],
          [1, 2]],
 
         [[1, 2],
          [1, 3],
          [2, 3]]], dtype=torch.int32),
 tensor([5., 3., 2.]))

In [6]:
edge_index = IntTensor([[0,1,2],[1,2,3]])
PathData.edge_index_kth_order_walk(edge_index, k=2)

tensor([[[0, 1],
         [1, 2]],

        [[1, 2],
         [2, 3]]], dtype=torch.int32)

In [7]:
edge_index = IntTensor([[0,1,2],[1,1,3]])
PathData.edge_index_kth_order_dag(edge_index, k=2)

IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

In [ ]:
IntTensor([[0,1,2],[1,1,3]]).size()

In [ ]:
IntTensor([[[0],[1],[2]],[[1],[1],[3]]]).size()

In [ ]:
IntTensor([[[0],[1],[2]],[[1],[1],[3]]]).reshape(IntTensor([[[0],[1],[2]],[[1],[1],[3]]]).size() + (1,))

In [ ]:
(1,2,3) + (1,)