# Temporal Graphs and Path Data

## Motivation and Learning Objectives

In this tutorial we will introduce the representation of temporal graph data in the `Temporal Graph` class and how such data can be used to calculate time respecting paths.


In [1]:
import torch
from torch_geometric.data import TemporalData
import numpy as np
import pathpyG as pp

pp.config['torch']['device'] = 'cpu'

## Temporal Graphs

Let's start with a simple temporal graph with four nodes `a`,`b`,`c`,`d` and seven timestamped edges `(b,c;2)`,`(a,b;1)`,`(c,d;3)`,`(d,a;4)`,`(b,d;2)`, `(d,a;6)`,`(a,b;7)`. 

The following code generates this temporal graph from the given edge list.

In [2]:
g = pp.TemporalGraph.from_edge_list([['b', 'c', 2],['a', 'b', 1], ['c', 'd', 3], ['d', 'a', 4], ['b', 'd', 2], ['d', 'a', 6], ['a', 'b', 7]])
print(g)

Temporal Graph with 4 nodes 5 edges and 7 time-stamped events in [1, 7]

Node attributes
	node_id		<class 'list'>

Graph attributes
	src		<class 'torch.Tensor'> -> torch.Size([7])
	dst		<class 'torch.Tensor'> -> torch.Size([7])
	num_nodes		<class 'int'>
	t		<class 'torch.Tensor'> -> torch.Size([7])



We can visualize a temporal graph by using the pathpyG plot function.

In [8]:
pp.plot(g, edge_color='lightgray')

Consistent with `pyG` the sources, destinations and timestamps are stored as a `pyG TemporalData` object, which we can access in the following way.



In [36]:
g.data

TemporalData(src=[7], dst=[7], t=[7], node_id=[4], num_nodes=4, edge_index=[2, 7])

In [37]:
print(g.data.t)

tensor([1, 2, 2, 3, 4, 6, 7])


With the generator functions `edges` and `temporal_edges` we can iterate through the (temporal) edges of this graph.

In [38]:
for v, w in g.edges:
    print(v, w)

a b
b c
b d
c d
d a
d a
a b


In [39]:
for v, w, t in g.temporal_edges:
    print(v, w, t)

a b 1
b c 2
b d 2
c d 3
d a 4
d a 6
a b 7


## Reading Temporal Graphs from CSV files

In [2]:
t = pp.TemporalGraph.from_csv('ants_1_1.tedges')
print(t)

Temporal Graph with 89 nodes 947 edges and 1911 time-stamped events in [0, 1438]

Node attributes
	node_id		<class 'list'>

Graph attributes
	num_nodes		<class 'int'>
	src		<class 'torch.Tensor'> -> torch.Size([1911])
	t		<class 'torch.Tensor'> -> torch.Size([1911])
	dst		<class 'torch.Tensor'> -> torch.Size([1911])



In [6]:
t = pp.TemporalGraph.from_csv('manufacturing_email.tedges', time_rescale=20)
print(t)

Temporal Graph with 167 nodes 5784 edges and 82927 time-stamped events in [63122700, 64294224]

Node attributes
	node_id		<class 'list'>

Graph attributes
	num_nodes		<class 'int'>
	src		<class 'torch.Tensor'> -> torch.Size([82927])
	t		<class 'torch.Tensor'> -> torch.Size([82927])
	dst		<class 'torch.Tensor'> -> torch.Size([82927])



## Extracting Causal Topologies via Node-Time Event DAGs

We are often interested in the time respecting paths of a temporal graph.

A time respecting path is defined as a sequence of nodes $v_0,...,v_l$ where the corresponding edges occur in the right time ordering and with a maximum time difference of $\delta\in \N$. 

In order to extract those paths out of a temporal graph, we have to construct a time-unfolded directed acyclic graph (DAG) that represents the network and captures all causal structures.

The nodes of a DAG are node-time-events of the temporal graph, i.e a node `a-t` represents the node `a` at time `t`. 

Two nodes `a-t` and `b-t'` are connected (with exceptions, see code ) if `a-t` directly influences `b-t'` 


In [40]:
dag = pp.algorithms.temporal_graph_to_event_dag(g, delta=1)
print(dag)

print(dag.data['node_id'])
print(dag.data.edge_index)

pp.plot(dag, edge_color='lightgray')

Graph with 9 nodes and 7 edges

Node attributes
	node_id		<class 'list'>
	node_name		<class 'list'>
	node_idx		<class 'list'>

Edge attributes
	edge_ts		<class 'torch.Tensor'> -> torch.Size([7])

Graph attributes
	num_nodes		<class 'int'>

['a-1', 'b-2', 'c-3', 'd-3', 'd-4', 'a-5', 'd-6', 'a-7', 'b-8']
tensor([[0, 1, 1, 2, 4, 6, 7],
        [1, 2, 3, 4, 5, 7, 8]])


With the following code, we can extract DAGs with only one single root node, which is not influenced by any other node-time event in the temporal graph.

In [42]:
x = pp.algorithms.extract_causal_trees(dag)
print(x)

{'a-1': tensor([[0, 1, 1, 2, 4],
        [1, 2, 3, 4, 5]], dtype=torch.int32), 'd-6': tensor([[6, 7],
        [7, 8]], dtype=torch.int32)}


## Higher-Order De Bruijn Graph Models for Causal Paths

With the DAG, we can now extract the time-respecting paths in our temporal graph.

In [43]:
paths = pp.PathData.from_temporal_dag(dag)
print(paths.paths[0])
print(paths.paths[1])
print(g.node_index_to_id)

tensor([[0, 1, 1, 2, 4],
        [1, 2, 3, 4, 5]])
tensor([[6, 7],
        [7, 8]])
{0: 'b', 1: 'c', 2: 'a', 3: 'd'}


The path data allows us to construct a Higher-Order De Bruijn Graph model belong to our temporal network.

In [45]:
g2 = pp.HigherOrderGraph(paths, order=2, node_id=g.data['node_id'])
pp.plot(g2)

In a nutshell, the following shows the steps that are needed to construct a Higher Order Graph. Here we construct our temporal graph from a `pyG TemporalData` by providing the sources, distances and timestamps.

In [52]:
# Create temporal network
d = TemporalData(src=[0,2,1,2,0,2,1,2], dst=[2,3,2,4,2,3,2,4], t=[1,2,3,4,5,6,7,8])
g = pp.TemporalGraph.from_pyg_data(d, node_id=['a', 'b', 'c', 'd', 'e'])

# Create event DAG and extract path data
dag = pp.algorithms.temporal_graph_to_event_dag(g, delta=1)
paths = pp.PathData.from_temporal_dag(dag)

# Create Higher Order Graph
g2 = pp.HigherOrderGraph(paths, order=2, node_id=g.data.node_id)
pp.plot(g2)

We can also skip the step of creating an event DAG by just using the following code.

In [53]:
g2 = pp.HigherOrderGraph.from_temporal_graph(g, delta=1, order=2)
pp.plot(g2)